---
- name: Play with EC2 and controller bits
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Debug job id
      ansible.builtin.debug:
        msg: "{{ awx_job_id | default(null) }}"

    - name: Debug nullity
      ansible.builtin.debug:
        msg: "{{ blah123 | default(null) }}"

    - name: Dump all facts
      ansible.builtin.debug:
        var: ansible_facts
