---
- name: Play with EC2 and controller bits
  hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  tasks:
    - name: Dump facts
      ansible.builtin.debug:
        var: ansible_facts
