---
- name: Play with EC2 and controller bits
  hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  tasks:
    - name: Gather EC2 metadata facts
      amazon.aws.ec2_metadata_facts:

    - name: Set vars from EC2 metadata
      ansible.builtin.debug:
        var: ansible_facts.ansible_ec2_placement_availability_zone
